### PR TITLE
(928) Send correction param everywhere and prevent double-clicking buttons

### PR DESCRIPTION
**Pull request by CristinaRO**

### CODE REVIEW

**Comment by james** [comment]
`data: 'prevent-double-click'` is working, but we can change it if needed. Just not sure why.

As for the correction param in URLs, we may be able to remove it from some of the confirmation pages, where the submission already exists and it knows it's a correction, but we'll still need it wherever we're creating a new submission. I'm not entirely sure what you mean by 'form parameters'

**Comment by tekin** [comment]
> data: 'prevent-double-click' is working, but we can change it if needed. Just not sure why.

Weirdly I can't see the attribute when I run it locally. e.g. the submission new page:

```
> document.forms[0].getElementsByClassName('govuk-button')[0].getAttribute('data-prevent-double-click')
< null
```

> As for the correction param in URLs, we may be able to remove it from some of the confirmation pages, where the submission already exists and it knows it's a correction, but we'll still need it wherever we're creating a new submission. I'm not entirely sure what you mean by 'form parameters'

e.g. https://github.com/dxw/DataSubmissionService/blob/cdaa74eb38a078f0063b6ba85293a1a61d7a301f/app/views/submissions/new.html.haml#L24

**Comment by mec** [comment]
Is the ```data-disable-with``` working here? Part of Rails UJS? That's why you see the disabled behaviour without the data attribute from GOVUK?

**Comment by CristinaRO** [comment]
@mec Changes done!

**Comment by james** [comment]
@tekin Double click protection is not working at the moment. You can try it out on staging. This commit adds double click protection, it did either way we added the `prevent-double-click` attribute, not entirely sure on the semantics behind the scenes, but it works!

**Comment by mec** [comment]
It's working. I can see both UJS and the GOVUK one working, as long as we are consistant.

**Comment by tekin** [comment]
Yeah, I think UJS works in a way that is not connected to the `prevent-double-click` data attribute. That is very much a GOVUK frontend toolkit thing. I have a feeling that "working" was the UJS version triggering. Without the attribute actually present and set to `true`, I can't see how the GOVUK JS would have triggered.

**Pull request merged**
