### PR TITLE
Add skylight gem

### PR DESCRIPTION
**Pull request by james**
As this project is open source, the SKYLIGHT_AUTHENTICATION setting should be set in an ENV varibiable.

### CODE REVIEW

**Comment by tekin** [comment]
can we set the env var in `docker-compose.env.sample` so it appears in the codebase?

**Comment by leeky** [comment]
@tekin Is that appropriate? It shouldn't be set in Docker for local dev.

**Comment by tekin** [comment]
@leeky OK, when I said "set" I meant just list an empty variable:

```
SKYLIGHT_AUTHENTICATION=
```

Agreed that this shouldn't be set in somebody's development environment (except for when testing the integration). I guess because we haven't got it anywhere else, I see the `docker-compose.env.sample` file as the list of the environment variables the application has. Perhaps what we actually need is a `ENVIRONMENT-VARIABLES.md` document that explains what each one is...

**Comment by tekin** [comment]
yep, agreed. documentation is something that's on my mind and I would like to talk about more in general, especially with new folks joining the team in the new year.

**Pull request merged**
